const db = require('../db')
const { Year, Movie } = require('../models')

db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
    const genxB = await Year.find({ year:'Generation X (Begin 1965-1970)'})
    const genxM = await Year.find({ year:'Generation X (Mid 1970-1975)'})
    const genxE = await Year.find({ year:'Generation X (End 1975-1980)'})
    const millB = await Year.find({ year:'Millennial (Begin 1981-1986)'})
    const millM = await Year.find({ year:'Millennial (Mid 1986-1991)'})
    const millE = await Year.find({ year:'Millennial (End 1991-1996)'})
    const genzB = await Year.find({ year:'Generation Z (Begin 1997-2002)'})
    const genzM = await Year.find({ year:'Generation Z (Mid 2002-2007)'})
    const genzE = await Year.find({ year:'Generation Z (End 2007-2012)'})

  const movies = [
    {
        year_id: genxE[0]._id,
        image: "https://assets.scriptslug.com/live/img/posters/x/_posterPageWebp/5819/halloween-1978.webp?utime=20240519142120",
        title: "Halloween (1978)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by John Carpenter, this slasher film follows Michael Myers as he stalks and kills teenage babysitters on Halloween night. It's credited with popularizing the slasher genre and has become a horror classic.",
        link: "https://youtu.be/sfZnbUf-tUE",
    },
    {
        year_id: genxB[0]._id,
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Night_of_the_Living_Dead_%281968%29_poster.jpg/220px-Night_of_the_Living_Dead_%281968%29_poster.jpg",
        title: "Night of the Living Dead (1968)",
        genre: "Horror",
        rated: "Unrated",
        summary: "Directed by George A. Romero, this groundbreaking zombie film depicts a group of people trapped in a farmhouse as they fend off hordes of flesh-eating zombies.",
        link: "https://youtu.be/pd5a0gs-UCQ",
    },
    {
        year_id: genxM[0]._id,
        image: "https://m.media-amazon.com/images/I/51276E72APL._SX300_SY300_QL70_FMwebp_.jpg",
        title: "The Texas Chain Saw Massacre (1974)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by Tobe Hooper, this film follows a group of friends who encounter a family of cannibals while visiting an old homestead, with Leatherface becoming one of horror's most iconic villains.",
        link: "https://youtu.be/BKn9QIaMgtQ",
    },
    {
        year_id: genxB[0]._id,
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/2036/20369574_sa.jpg;maxHeight=150;maxWidth=200",
        title: "The Birds (1963)",
        genre: "Horror",
        rated: "PG-13",
        summary: "Directed by Alfred Hitchcock, this film might be a bit earlier than your specified timeframe but is worth mentioning. It's a suspenseful horror film about a small California town under siege by aggressive birds.",
        link: "https://youtu.be/towd2xnkd9U",
    },
    {
        year_id: genxM[0]._id,
        image: "https://i.ebayimg.com/images/g/MLIAAOSwxdZiNMOH/s-l1600.webp",
        title: "The Exorcist (1973)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by William Friedkin, this film follows the demonic possession of a young girl and the attempts by two priests to save her soul through an exorcism. It's widely considered one of the scariest movies ever made.",
        link: "https://youtu.be/YDGw1MTEe9k",
    },
    {
        year_id: millB[0]._id,
        image: "https://m.media-amazon.com/images/I/514-4yC5uUL._SX300_SY300_QL70_FMwebp_.jpg",
        title: "A Nightmare on Elm Street (1984)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by Wes Craven, this film introduces the iconic villain Freddy Krueger, who haunts the dreams of teenagers in the fictional town of Springwood. It's praised for its inventive premise and imaginative kills.",
        link: "https://youtu.be/dCVh4lBfW-c",
    },
    {
        year_id: millB[0]._id,
        image: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/the-shining-1980/large_zc5y5OwKSV9MDXpfWxwrOjyRHsq.jpg",
        title: "The Shining (1980)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by Stanley Kubrick, based on the novel by Stephen King. This psychological horror film follows a family who becomes the caretakers of an isolated hotel, where supernatural forces drive the father to madness.",
        link: "https://youtu.be/S014oGZiSdI"
    },
    {
        year_id: millE[0]._id,
        image: "https://blob.cede.ch/catalog/17419000/17419965_1_92.jpg?v=1",
        title: "The Silence of the Lambs (1991)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by Jonathan Demme, based on the novel by Thomas Harris. While primarily a psychological thriller, this film contains elements of horror, especially in its portrayal of the serial killer Hannibal Lecter. It follows FBI trainee Clarice Starling as she seeks the help of Lecter to catch another serial killer.",
        link: "https://youtu.be/6iB21hsprAQ",
    },
    {
        year_id: millB[0]._id,
        image: "https://sidewalkfest.com/wp-content/uploads/2023/10/xPazCcKp62IshnLVf9BLAjf9vgC-1024x1536.jpg",
        title: "Poltergeist (1982)",
        genre: "Horror",
        rated: "Rated PG",
        summary: "Directed by Tobe Hooper, with Steven Spielberg as a co-writer and producer, this film follows a family whose suburban home is invaded by malevolent ghosts. It's renowned for its special effects and suspenseful atmosphere.",
        link: "https://youtu.be/9eZgEKjYJqA",
    },
    {
        year_id: millE[0]._id,
        image: "https://m.media-amazon.com/images/I/5127F505WAL._SX300_SY300_QL70_FMwebp_.jpg",
        title: "Scream (1996)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by Wes Craven, this meta-horror film revitalized the slasher genre by subverting its tropes and incorporating self-aware humor. It follows a masked killer terrorizing a small town, with a savvy group of teenagers fighting back.",
        link: "https://youtu.be/i3J6ACKQ7K0",
    },
    {
        year_id: genzB[0]._id,
        image: "https://static.wikia.nocookie.net/disney/images/6/66/The_sixth_sense.jpg/revision/latest/scale-to-width-down/1000?cb=20230311195554",
        title: "The Sixth Sense (1999)",
        genre: "Horror",
        rated: "Rated PG-13",
        summary: "Directed by M. Night Shyamalan, this supernatural thriller follows a young boy who communicates with the dead and the psychologist who tries to help him. It's known for its twist ending.",
        link: "https://youtu.be/3-ZP95NF_Wk"
    },
    {
        year_id: genzB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMTY2ODc2NTQ2OF5BMl5BanBnXkFtZTYwNzA4OTU3._V1_.jpg",
        title: "The Ring (2002)",
        genre: "Horror",
        rated: "Rated PG-13",
        summary: "Directed by Gore Verbinski, this supernatural horror film follows a journalist investigating a cursed videotape that leads to the death of anyone who watches it seven days later.",
        link: "https://youtu.be/mTACCgSWu8E"
    },
    {
        year_id: genzE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMjY1NjcxODQ4MV5BMl5BanBnXkFtZTcwMzUxNjM4Mg@@._V1_FMjpg_UX1000_.jpg",
        title: "Paranormal Activity (2007)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by Oren Peli, this found-footage supernatural horror film follows a young couple who set up cameras to document the paranormal activity haunting their home.",
        link: "https://youtu.be/F_UxLEqd074"
    },
    {
        year_id: genzM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BM2M1MzI1MWYtYmM2ZC00OWY3LTk0ZGMtNmRkNzU1NzEzMWE5XkEyXkFqcGdeQXVyODUwOTkwODk@._V1_FMjpg_UX1000_.jpg",
        title: "Saw (2004)",
        genre: "Horror",
        rated: "Rated R",
        summary: "Directed by James Wan, this psychological horror film follows two men who wake up chained in a dilapidated bathroom and are forced to play a deadly game orchestrated by a sadistic serial killer known as Jigsaw. It's known for its inventive traps and moral dilemmas.",
        link: "https://youtu.be/S-1QgOMQ-ls",
    },
    {
        year_id: genzM[0]._id,
        image: "https://horrorhothousereview.wordpress.com/wp-content/uploads/2013/06/the-grudge-_2004_.jpg",
        title: "The Grudge (2004)",
        genre: "Horror",
        rated: "Rated PG-13",
        summary: "Directed by Takashi Shimizu, this supernatural horror film follows a curse that manifests as a vengeful ghost in a house in Tokyo. It's a remake of the Japanese film 'Ju-On: The Grudge' and is known for its eerie atmosphere and hair-raising scares.",
        link: "https://youtu.be/_Amj1SVOf4U",
    },
    {
        year_id: genxB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BOTAzMTJkYTQtYTdkOS00OTNiLWFmMDctMzcwNGJhYTY4OGM5XkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_.jpg",
        title: "The Graduate (1967)",
        genre: "Comedy",
        rated: "Rated PG",
        summary: "Directed by Mike Nichols, this comedy-drama follows a recent college graduate who has an affair with an older woman and then falls in love with her daughter. It's acclaimed for its witty dialogue, memorable performances, and iconic soundtrack.",
        link: "https://youtu.be/6KnSucVko1s",
    },
    {
        year_id: genxB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMTYyNDQwOTc5NF5BMl5BanBnXkFtZTYwNjk5OTM5._V1_.jpg",
        title: "The Odd Couple (1968)",
        genre: "Comedy",
        rated: "Rated G",
        summary: "Directed by Gene Saks, this comedy film follows two mismatched roommates, one neat and uptight, the other sloppy and easygoing, as they navigate life together after their respective marriages end in divorce.",
        link: "https://youtu.be/33ZvO26hP7M"
    },
    {
        year_id: genxM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BZGZmMWE1MDYtNzAyNC00MDMzLTgzZjQtNTQ5NjYzN2E4MzkzXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
        title: "Blazing Saddles (1974)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by Mel Brooks, this satirical Western comedy follows a black sheriff who is appointed to a racially divided town in the Old West. It's celebrated for its irreverent humor, sharp social commentary, and memorable one-liners.",
        link: "https://youtu.be/VKayG1TrfuE",
    },
    {
        year_id: genxM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BN2IyNTE4YzUtZWU0Mi00MGIwLTgyMmQtMzQ4YzQxYWNlYWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        title: "Monty Python and the Holy Grail (1975)",
        genre: "Comedy",
        rated: "Rated PG",
        summary: "Directed by Terry Gilliam and Terry Jones, this British comedy follows King Arthur and his knights as they embark on a surreal quest for the Holy Grail. It's renowned for its absurd humor, quotable lines, and innovative animation.",
        link: "https://youtu.be/6yOIjSF8tmo",
    },
    {
        year_id: genxE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BOGI2NDI3OGQtNTE4Mi00YmYwLThmMTItMzU5MzQ3ZGUyMWJjXkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_.jpg",
        title: "Animal House (1978)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by John Landis, this comedy follows the misadventures of a rowdy fraternity at a fictional college in the early 1960s. It's considered one of the greatest comedies of all time, known for its raucous humor and memorable characters.",
        link: "https://youtu.be/KWjtI6n5xWM",
    },
    {
        year_id: millB[0]._id,
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.scriptslug.com%2Fscript%2Fghostbusters-1989&psig=AOvVaw0KzzBjRGCMWhdjyKVpczOJ&ust=1717271685242000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCICBwdzVuIYDFQAAAAAdAAAAABAE",
        title: "Ghostbusters (1984)",
        genre: "Comedy",
        rated: "Rated PG",
        summary: "Directed by Ivan Reitman, this supernatural comedy follows a group of eccentric parapsychologists who start a ghost-catching business in New York City. It's beloved for its blend of humor, supernatural elements, and memorable characters.",
        link: "https://youtu.be/wQAljlSmjC8",
    },
    {
        year_id: millE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BZDQwMjNiMTQtY2UwYy00NjhiLTk0ZWEtZWM5ZWMzNGFjNTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        title: "Dumb and Dumber (1994)",
        genre: "Comedy",
        rated: "Rated PG-13",
        summary: "Directed by Peter Farrelly, this slapstick comedy follows two well-meaning but dimwitted friends who embark on a cross-country road trip to return a briefcase full of money.",
        link: "https://youtu.be/l13yPhimE3o"
    },
    {
        year_id: millM[0]._id,
        image: "https://s3.us-east-1.amazonaws.com/mt-website-prod-contentbucket-1tg1jr7b5zn9a/images/movie-posters/HO00005195.jpg",
        title: "Ferris Bueller's Day Off (1986)",
        genre: "Comedy",
        rated: "Rated PG-13",
        summary: "Directed by John Hughes, this teen comedy follows high school student Ferris Bueller as he skips school and embarks on a series of adventures in Chicago.",
        link: "https://youtu.be/0ZDbKhkLxTs"
    },
    {
        year_id: millM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNWRjZmFlMDAtZjljYy00YjUwLTgyMDQtMTI5ZjhiZTNkNDNhXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_FMjpg_UX1000_.jpg",
        title: "Planes, Trains and Automobiles (1987)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by John Hughes, this buddy comedy follows an uptight businessman and a bumbling shower curtain ring salesman who find themselves stuck together on a chaotic journey home for Thanksgiving. It's celebrated for its heartfelt moments and comedic chemistry between Steve Martin and John Candy.",
        link: "https://youtu.be/ZfnvrPZSFb8",
    },
    {
        year_id: millB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BZjA3YjdhMWEtYjc2Ni00YzVlLWI0MTUtMGZmNTJjNmU0Yzk2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        title: "Airplane! (1980)",
        genre: "Comedy",
        rated: "Rated PG",
        summary: "Directed by Jim Abrahams, David Zucker, and Jerry Zucker, this parody film satirizes the disaster film genre, particularly the 1957 film 'Zero Hour!'. It's known for its rapid-fire jokes, slapstick humor, and memorable quotes.",
        link: "https://youtu.be/07pPmCfKi3U",
    },
    {
        year_id: genzB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNDQwMTAzOTkxNV5BMl5BanBnXkFtZTgwMjc0MTAwMjE@._V1_.jpg",
        title: "The Big Lebowski (1998)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by Joel and Ethan Coen, this quirky comedy follows 'The Dude', a laid-back slacker who gets embroiled in a convoluted kidnapping plot. It's praised for its offbeat humor, memorable characters, and clever dialogue.",
        link: "https://youtu.be/cd-go0oBF4Y",
    },
    {
        year_id: genzM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMTQ2MzYwMzk5Ml5BMl5BanBnXkFtZTcwOTI4NzUyMw@@._V1_FMjpg_UX1000_.jpg",
        title: "Anchorman: The Legend of Ron Burgundy (2004)",
        genre: "Comedy",
        rated: "Rated PG-13",
        summary: "Directed by Adam McKay, this satire follows a chauvinistic news anchor and his misfit team as they compete for dominance in a male-dominated industry. It's known for its absurd humor, memorable quotes, and comedic performances.",
        link: "https://youtu.be/QvJ1K0_JzFI",
    },
    {
        year_id: genzM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BY2VkMDg4ZTYtN2M3Yy00NWZiLWE2ODEtZjU5MjZkYWNkNGIzXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_FMjpg_UX1000_.jpg",
        title: "Superbad (2007)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by Greg Mottola, this coming-of-age comedy follows two high school friends who embark on a wild night of misadventures before their separation for college. It's praised for its raunchy humor, authentic portrayal of teenage friendship, and heartfelt moments.",
        link: "https://youtu.be/4eaZ_48ZYog",
    },
    {
        year_id: genzE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMjAyOTMyMzUxNl5BMl5BanBnXkFtZTcwODI4MzE0NA@@._V1_FMjpg_UX1000_.jpg",
        title: "Bridesmaids (2011)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by Paul Feig, this comedy follows a woman who struggles to compete with her best friend's new, wealthy friend while serving as her maid of honor. It's acclaimed for its hilarious performances, sharp writing, and portrayal of female friendships.",
        link: "https://youtu.be/FNppLrmdyug",
    },
    {
        year_id: genzE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        title: "The Hangover (2009)",
        genre: "Comedy",
        rated: "Rated R",
        summary: "Directed by Todd Phillips, this comedy follows a group of friends who go to Las Vegas for a bachelor party and wake up the next morning with no memory of the previous night's events, trying to piece together what happened.",
        link: "https://youtu.be/tcdUhdOlz9M"
    },
    {
        year_id: genxM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMjA1N2JlMjItMTExZC00NTIxLWE2YTYtY2ZkM2M5OWM3M2YyXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg",
        title: "The Towering Inferno (1974)",
        genre: "Action, Drama, Thriller",
        rated: "Rated PG",
        summary: "Directed by John Guillermin and Irwin Allen, this disaster film follows the efforts of firefighters and other personnel to extinguish a massive fire in a high-rise building.",
        link: "https://youtu.be/tgWgUUT-YW4"
    },
    {
        year_id: genxM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNGZiMTkyNzQtMDdmZi00ZDNkLWE4YTAtZGNlNTIzYzQyMGM2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_FMjpg_UX1000_.jpg",
        title: "Enter the Dragon (1973)",
        genre: "Action, Crime, Drama",
        rated: "Rated R",
        summary: "Directed by Robert Clouse, this martial arts film stars Bruce Lee as a martial artist who is recruited by a British intelligence agent to infiltrate the island fortress of a crime lord.",
        link: "https://youtu.be/5RGju9NuoOU"
    },
    {
        year_id: genxM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMzdhMTM2YTItOWU2YS00MTM0LTgyNDYtMDM1OWM3NzkzNTM2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg",
        title: "Dirty Harry (1971)",
        genre: "Action",
        rated: "Rated R",
        summary: "Directed by Don Siegel, this crime thriller follows a tough San Francisco cop known as 'Dirty Harry' as he tracks down a serial killer. It's praised for Clint Eastwood's iconic performance, gritty realism, and iconic catchphrases.",
        link: "https://youtu.be/YgRjIEwMYQ4",
    },
    {
        year_id: genxE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_.jpg",
        title: "Star Wars: Episode IV - A New Hope (1977)",
        genre: "Action",
        rated: "Rated PG",
        summary: "Directed by George Lucas, this space opera follows a young farm boy who joins a rebellion against an evil empire and learns the ways of the Force from a wise Jedi knight. It's praised for its groundbreaking visual effects, imaginative world-building, and iconic characters.",
        link: "https://youtu.be/vZ734NWnAHA",
    },
    {
        year_id: genxE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMTM4Mjg5ODEzMV5BMl5BanBnXkFtZTcwMDc3NDk0NA@@._V1_.jpg",
        title: "Mad Max (1979)",
        genre: "Action, Adventure, Sci-Fi",
        rated: "Rated R",
        summary: "Directed by George Miller, this post-apocalyptic action film follows Max Rockatansky, a police officer in a dystopian Australia, as he seeks revenge against a biker gang who killed his family.",
        link: "https://youtu.be/caHnaRq8Qlg"
    },
    {
        year_id: millB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        title: "The Terminator (1984)",
        genre: "Action",
        rated: "Rated R",
        summary: "Directed by James Cameron and starring Arnold Schwarzenegger as the titular cyborg assassin, this sci-fi action film follows a woman who is targeted by a killer robot sent from the future. It's acclaimed for its groundbreaking special effects, thrilling chase sequences, and iconic catchphrases.",
        link: "https://youtu.be/nGrW-OR2uDk",
    },
    {
        year_id: millM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        title: "Die Hard (1988)",
        genre: "Action",
        rated: "Rated R",
        summary: "Directed by John McTiernan and starring Bruce Willis as NYPD officer John McClane, this action film follows McClane as he single-handedly takes on a group of terrorists who have taken hostages in a Los Angeles skyscraper. It's considered one of the greatest action films ever made, known for its tense atmosphere, memorable one-liners, and charismatic lead.",
        link: "https://youtu.be/gYWvwkXreaI",
    },
    {
        year_id: millM[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BZTllNWNlZjctMWQwMS00ZDc3LTg5ZjMtNzhmNzhjMmVhYTFlXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg",
        title: "Lethal Weapon (1987)",
        genre: "Action, Crime, Thriller",
        rated: "Rated R",
        summary: "Directed by Richard Donner, this buddy cop film follows two LAPD detectives, one a loose cannon and the other a veteran nearing retirement, as they investigate a drug-smuggling operation.",
        link: "https://youtu.be/bKeW-MGu-qQ"
    },
    {
        year_id: millE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNDc2NDQ0MDk3N15BMl5BanBnXkFtZTYwNDg3Mzk4._V1_.jpg",
        title: "Speed (1994)",
        genre: "Action, Thriller",
        rated: "Rated R",
        summary: "Directed by Jan de Bont, this action thriller follows a Los Angeles SWAT team officer who must prevent a bomb rigged to explode on a city bus if its speed drops below 50 mph.",
        link: "https://youtu.be/8piqd2BWeGI"
    },
    {
        year_id: millB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BODBmOWU2YWMtZGUzZi00YzRhLWJjNDAtYTUwNWVkNDcyZmU5XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
        title: "First Blood (1982)",
        genre: "Action",
        rated: "Rated R",
        summary: "Directed by Ted Kotcheff and starring Sylvester Stallone as John Rambo, this action film follows a Vietnam War veteran who becomes embroiled in a conflict with a small-town sheriff. It's praised for its portrayal of PTSD, intense action sequences, and Stallone's performance.",
        link: "https://youtu.be/oXngES_l_HQ",
    },
    {
        year_id: genzB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        title: "The Matrix (1999)",
        genre: "Action",
        rated: "Rated R",
        summary: "Directed by The Wachowskis, this sci-fi action film follows a computer hacker who discovers the true nature of reality and joins a rebellion against sentient machines. It's praised for its groundbreaking visual effects, innovative action sequences, and philosophical themes.",
        link: "https://youtu.be/vKQi3bBA1y8",
    },
    {
        year_id: genzB[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BM2JkNGU0ZGMtZjVjNS00NjgyLWEyOWYtZmRmZGQyN2IxZjA2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1000_.jpg",
        title: "The Bourne Identity (2002)",
        genre: "Action",
        rated: "Rated PG-13",
        summary: "Directed by Doug Liman and based on the novel by Robert Ludlum, this thriller follows an amnesiac who discovers he's a skilled assassin and must uncover his past while evading those who want him dead. It's praised for its intense action, gripping plot, and Matt Damon's performance.",
        link: "https://youtu.be/gjwE_8uFMbA",
    },
    {
        year_id: genzE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
        title: "The Dark Knight (2008)",
        genre: "Action",
        rated: "Rated PG-13",
        summary: "Directed by Christopher Nolan, this superhero film follows Batman as he faces off against the Joker, a deranged criminal mastermind wreaking havoc on Gotham City. It's acclaimed for its dark tone, complex characters, and Heath Ledger's iconic performance as the Joker.",
        link: "https://youtu.be/EXeTwQWrcwY",
    },
    {
        year_id: genzE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg",
        title: "Inception (2010)",
        genre: "Action",
        rated: "Rated PG-13",
        summary: "Directed by Christopher Nolan, this sci-fi action film follows a thief who enters the dreams of others to steal their secrets. It's praised for its mind-bending visuals, intricate plot, and thought-provoking themes.",
        link: "https://youtu.be/YoHD9XEInc0",
    },
    {
        year_id: genzE[0]._id,
        image: "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        title: "The Avengers (2012)",
        genre: "Action",
        rated: "Rated PG-13",
        summary: "Directed by Joss Whedon and based on the Marvel Comics superhero team, this film follows a group of superheroes who must come together to stop an alien invasion. It's celebrated for its action-packed sequences, humor, and ensemble cast.",
        link: "https://youtu.be/eOrNdBpGMv8",
    },
    {
        year_id: 1978,
        image: "https://m.media-amazon.com/images/M/MV5BZmUyMDEyOTgtZmUwOS00NTdkLThlNzctNTM1ODQ4M2VhMjdhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
        title: "Grease (1978)",
        genre: "Romance, Musical",
        rated: "Rated PG",
        summary: "Directed by Randal Kleiser, this musical romantic comedy is set in the 1950s and follows the romantic relationship between greaser Danny and Australian transfer student Sandy.",
        link: "https://youtu.be/THd96gHV7Tg"
    },
    {
        year_id: 1977,
        image: "https://m.media-amazon.com/images/I/91L8PmPjhSL._AC_UF894,1000_QL80_.jpg",
        title: "Annie Hall (1977)",
        genre: "Romance, Comedy",
        rated: "Rated PG",
        summary: "Directed by Woody Allen, this romantic comedy follows a neurotic comedian and his quirky relationship with a free-spirited woman. It's acclaimed for its innovative narrative structure, witty dialogue, and insightful commentary on love and relationships.",
        link: "https://youtu.be/OqVgCfZX-yE",
    },
    {
        year_id: 1970,
        image: "https://m.media-amazon.com/images/I/91yQY8V1whL._AC_UF894,1000_QL80_.jpg",
        title: "Love Story (1970)",
        genre: "Romance",
        rated: "Rated PG",
        summary: "Directed by Arthur Hiller, this romantic drama follows a wealthy Harvard student who falls in love with a working-class girl, leading to tragedy. It's remembered for its iconic line 'Love means never having to say you're sorry' and its emotional impact.",
        link: "https://youtu.be/eprwTDVTEb8",
    },
    {
        year_id: 1965,
        image: "https://m.media-amazon.com/images/M/MV5BZGM3Yzg5NTQtMTlkYS00MzQ1LWIyY2YtYWM0YjkzOWI2OTc3XkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_.jpg",
        title: "Doctor Zhivago (1965)",
        genre: "Romance",
        rated: "Rated PG-13",
        summary: "Directed by David Lean and based on the novel by Boris Pasternak, this epic romance follows the life of a Russian physician and poet during the Russian Revolution. It's praised for its sweeping cinematography, emotional depth, and timeless love story.",
        link: "https://youtu.be/CGGr21PilKY",
    },
    {
        year_id: 1980,
        image: "https://m.media-amazon.com/images/I/81CMmHKcgQL._AC_UF894,1000_QL80_.jpg",
        title: "The Blue Lagoon (1980)",
        genre: "Romance",
        rated: "Rated R",
        summary: "Directed by Randal Kleiser and based on the novel by Henry De Vere Stacpoole, this romantic adventure follows two young cousins stranded on a tropical island who develop a romantic relationship as they come of age. It's known for its lush cinematography and controversial themes.",
        link: "https://youtu.be/A0UapwJIJn8",
    },
    // {
    //     year_id: genxB[0]._id,
    //     image: { type: String, required: true },
    //     title: { type: String, required: true },
    //     genre: { type: String, required: true },
    //     rated: { type: String, required: true },
    //     summary: { type: String, required: true },
    //     link: { type: String, required: true },
    // },
]

await Movie.insertMany(movies)
console.log('Created movies with years!')
}
const run = async () => {
await main()
db.close()
}

run()